global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mysql-exporter
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: mongodb-exporter
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
